### ISSUE TITLE
Activity, Money 클래스 등의 코드는 도서에 포함되어 있지 않습니다

### ISSUE THREAD

**Issue by jcw1031** [wikibook/clean-architecture#2]
안녕하세요. 최근에 `만들면서 배우는 클린 아키텍처` 도서를 대여하여 학습 중인 학생입니다
`04장 유스케이스 구현하기` 부터 `Account` 클래스를 시작으로 예제 코드와 함께 설명이 나오는데, `Activity`, `Money` 클래스에 대한 내용은 도서에서 다루지 않고 예제 코드에서만 확인할 수 있었습니다.
혹시 해당 코드들은 설명이 굳이 필요하지 않다고 판단하여 도서에서 제외된 걸까요??

**Comment by wikibook** [comment]
@jcw1031 님, 안녕하세요. 위키북스 담당자입니다.

말씀해 주신 부분에 대해서는 특별히 저자도 책에서 언급하는 바는 없지만 이 책의 논의 초점에서 벗어난 대상이기 때문인 것 같습니다. 이 책에서는 클린 아키텍처를 비롯해 아키텍처 관점에서 다뤄야 할 내용들을 초점을 맞추고 있어서 특정 클래스 구현까지 모두 본문에서 다루지는 않은 듯하고, 예제 코드를 통해 구현 내용을 파악할 수 있도록 구성한 것으로 보입니다. 본문 v~vi쪽의 서문 내용을 보시면 이 책이 목표하는 바와 논의 주제를 조금 더 구체적으로 확인하실 수 있습니다.

그럼 참고 부탁드리고요, 충분한 답변이 되셨으면 좋겠습니다. 
오늘도 좋은 하루 보내세요.
고맙습니다.

**Comment by jcw1031** [comment]
아하 역시 그렇군요~~
답변 감사합니다!!😁

**Comment by wikibook** [comment]
@jcw1031 님, 빠른 확인 감사합니다..! :)
