### ISSUE TITLE
7장: AccountTest와 ActivityWindowTest의 패키지 위치 이슈

### ISSUE THREAD

**Issue by aaronsleepy** [wikibook/clean-architecture#3]
`AccountTest`와 `ActivityWindowTest` 클래스에 선언된 패키지는 `io.reflectoring.buckpal.account.domain`입니다.

반면 실제 클래스의 위치는 `application` 하위에 있어서 에러가 납니다
![image](https://github.com/wikibook/clean-architecture/assets/89061309/128e476b-cfac-4421-af28-810d8493ba87)

test의 `domain` 패키지를 `application` 상위에 있는 `account` 패키지로 옮겨야 할 것 같아요

**Comment by wikibook** [comment]
@aaronsleepy 님, 안녕하세요.
위키북스 담당자입니다.

보내주신 내용을 확인했는데 파일 위치가 잘못되었던 것 같습니다. 말씀하신 대로 `domain` 패키지를 `account` 패키지 아래로 옮겼습니다.

불편을 드려 죄송하고, 꼼꼼하게 확인해 주셔서 정말 감사합니다.
그럼 오늘도 좋은 하루 보내세요!
고맙습니다.
